/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Dealer = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllDealers' : IDL.Func([], [IDL.Vec(Dealer)], ['query']),
  'getDealersByCity' : IDL.Func([IDL.Text], [IDL.Vec(Dealer)], ['query']),
  'getDealersByState' : IDL.Func([IDL.Text], [IDL.Vec(Dealer)], ['query']),
  'submitInquiry' : IDL.Func([Inquiry], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Dealer = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllDealers' : IDL.Func([], [IDL.Vec(Dealer)], ['query']),
    'getDealersByCity' : IDL.Func([IDL.Text], [IDL.Vec(Dealer)], ['query']),
    'getDealersByState' : IDL.Func([IDL.Text], [IDL.Vec(Dealer)], ['query']),
    'submitInquiry' : IDL.Func([Inquiry], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };